import { IMenu } from '../../../../../front-components/src/lib/shared/models';
import { IconType } from '../../../../../front-components/src/lib/shared/models';

export const MENU: IMenu[] = [
	{
		title: 'Typography',
		toolTip: 'Typography',
		link: 'components/typography',
		active: true,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Icons',
		toolTip: 'Icons',
		link: 'components/icons',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Dividers',
		toolTip: 'Dividers',
		link: 'components/dividers',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Buttons',
		toolTip: 'Buttons',
		link: 'components/buttons',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Close buttons',
		toolTip: 'Close buttons',
		link: 'components/close-buttons',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Utility buttons',
		toolTip: 'Utility buttons',
		link: 'components/utility-buttons',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Preview button',
		toolTip: 'Preview button',
		link: 'components/preview-button',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Backdrop button',
		toolTip: 'Backdrop button',
		link: 'components/backdrop-button',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Links',
		toolTip: 'Links',
		link: 'components/links',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Nav buttons',
		toolTip: 'Nav buttons',
		link: 'components/nav-buttons',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Avatar',
		toolTip: 'Avatar',
		link: 'components/avatar',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Avatar dropdown',
		toolTip: 'Avatar dropdown',
		link: 'components/avatar-dropdown',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Badges',
		toolTip: 'Badges',
		link: 'components/badges',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Status icons',
		toolTip: 'Status icons',
		link: 'components/status-icons',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Tags',
		toolTip: 'Tags',
		link: 'components/tags',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Chips',
		toolTip: 'Chips',
		link: 'components/chips',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Form fields',
		toolTip: 'Form fields',
		link: 'components/form-fields',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Select dropdown',
		toolTip: 'Select dropdown',
		link: 'components/select-dropdown',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Multiselect',
		toolTip: 'Multiselect',
		link: 'components/multiselect',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Search select',
		toolTip: 'Search select',
		link: 'components/search-select',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Accordion',
		toolTip: 'Accordion',
		link: 'components/accordion',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Number picker',
		toolTip: 'Number picker',
		link: 'components/number-picker',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'OTP input',
		toolTip: 'OTP input',
		link: 'components/otp-input',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Checkboxes',
		toolTip: 'Checkboxes',
		link: 'components/checkboxes',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Toggles',
		toolTip: 'Toggles',
		link: 'components/toggles',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Tabs',
		toolTip: 'Tabs',
		link: 'components/tabs',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Action bar',
		toolTip: 'Action bar',
		link: 'components/action-bar',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Dialog header',
		toolTip: 'Dialog header',
		link: 'components/dialog-header',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Modal triggers',
		toolTip: 'Modal triggers',
		link: 'components/modal-triggers',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Side page trigger',
		toolTip: 'Side page trigger',
		link: 'components/side-page-trigger',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Popover',
		toolTip: 'Popover',
		link: 'components/popover',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Toast notifications',
		toolTip: 'Toast notifications',
		link: 'components/toast-notifications',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Tooltip',
		toolTip: 'Tooltip',
		link: 'components/tooltip',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Image upload progress',
		toolTip: 'Image upload progress',
		link: 'components/image-upload-progress',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Files upload',
		toolTip: 'Files upload',
		link: 'components/files-upload',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Empty state',
		toolTip: 'Empty state',
		link: 'components/empty-state',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Skeleton blocks',
		toolTip: 'Skeleton blocks',
		link: 'components/skeleton-blocks',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Scrollbar',
		toolTip: 'Scrollbar',
		link: 'components/scrollbar',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Carousel',
		toolTip: 'Carousel',
		link: 'components/carousel',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Table examples',
		toolTip: 'Table examples',
		link: 'components/table-examples',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
	{
		title: 'Load pagination',
		toolTip: 'Load pagination',
		link: 'components/load-pagination',
		active: false,
		icon: IconType.ImagePlus,
		subMenu: [],
	},
];
